name: Automated API tests using Postman CLI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Application
        run: |
          # Build application
  api-governance-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          # Lint your API using Postman CLI
          postman api lint --integration-id 137029
  unit-tests:
    needs: [build, api-governance-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: |
          # Run unit tests
  api-contract-tests:
    needs: [build, api-governance-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Cat Facts.json" --integration-id "137029-${{ github.run_id }}"
  deploy:
    needs: [unit-tests, api-contract-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: |
          # Deploy application
